---

#install and config nginx
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes

- name: start nginx
  systemd: name=nginx state=started
  become: yes

- name: copy the nginx config file and restart nginx
  copy: src=/home/foo/static_site.cfg dest=/etc/nginx/sites-available/static_site.cfg
  become: yes

- name: create symlink
  file: src=/etc/nginx/sites-available/static_site.cfg dest=/etc/nginx/sites-enabled/default state=link
  become: yes
  notify: restart nginx

#install and config php-fpm
- name: Install some required apt packages for the Sury repo
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - lsb-release

- name: Add the Sury apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: Configure the Sury repo
  apt_repository:
    filename: sury
    repo: 'deb https://packages.sury.org/php/ jessie main'

- name: Install the specified version of PHP-FPM
  apt:
    name: "php{{ php_fpm_version }}-fpm"
    state: "{{ php_fpm_state }}"
    purge: "{{ php_fpm_purge }}"

- name: Install additional PHP modules
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ php_fpm_modules }}"

- name: Set the PHP-FPM logrotate file
  template:
    src: logrotate/php-fpm.j2
    dest: "/etc/logrotate.d/php{{ php_fpm_version }}-fpm"
    owner: root
    group: root
    mode: 0644

- name: Set the php.ini file
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php_fpm_version }}/fpm/php.ini"
    owner: root
    group: root
    mode: 0644
  notify:
    - Check PHP-FPM config
    - Restart PHP-FPM

- name: Set the php-fpm.conf file
  template:
    src: php-fpm.conf.j2
    dest: "/etc/php/{{ php_fpm_version }}/fpm/php-fpm.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Check PHP-FPM config
    - Restart PHP-FPM

- name: Ensure PHP-FPM is running
  systemd:
    name: "php{{ php_fpm_version }}-fpm"
    enabled: yes
    state: started

- name: Define the pools
  template:
    src: pool.conf.j2
    dest: "/etc/php/{{ php_fpm_version }}/fpm/pool.d/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_fpm_pools }}"
  notify:
    - Check PHP-FPM config
    - Reload PHP-FPM

- name: Remove default www pool
  file:
    path: "/etc/php/{{ php_fpm_version }}/fpm/pool.d/www.conf"
    state: absent
  when: php_fpm_remove_default_www
  notify:
    - Check PHP-FPM config
    - Reload PHP-FPM

#Install PHP

- name: Install PHP CLI
  become: true
  apt:
    name: php5-cli
    state: latest
- name: Install PHP packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php7.1-cli
    - php7.1-curl
    - php7.1-intl
    - php7.1-mysql
- name: Set date.timezone for CLI
  become: true
  lineinfile:
    dest: /etc/php/7.1/cli/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = UTC"

- name: Set date.timezone for FPM
  become: true
  lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = UTC"